### ISSUE TITLE
Conflict with Qukeys

### ISSUE THREAD

**Issue by tiltowait** [tiltowait/Kaleidoscope-BetterShifting#1]
If a modifier is invoked via the [Qukeys](https://github.com/keyboardio/Kaleidoscope-Qukeys) plugin, it will break shifting rules. My suspicion is that `keyToggledOn()` is being called, but not `keyToggledOff()`, meaning `num_modifiers_on` isn't being decremented back to zero.

**Steps to reproduce:**
1. Configure a key in `Qukeys` to invoke a modifier (such as `Key_RightAlt`).
2. Hold that key down, invoking the modifier, then release.
3. Type an uppercase character using the shift on the same side as that key

**Expected result:** No character outputted.
**Actual result:** The uppercase character is outputted. Furthermore, after that point, the shifting rules will no longer apply.

**Comment by tiltowait** [comment]
8069990 contained a regression that broke the functionality of ignoring shifting rules while holding modifier keys. Reopening.

**Comment by algernon** [comment]
~What if you put `ProperShifting` in front of `Qukeys` in hour `KALEIDOSCOPE_INIT_PLUGINS()`? Does that help?~ On second thought, no, it won't.

I guess you could track shift state some other way, rather than looking at keycodes (because those will break with SpaceCadet and OneShot too). I think we have an example of that somewhere, I'll dig it up in a bit.

**Comment by algernon** [comment]
Ok, so we have `kaleidoscope::hid::isModifierKeyActive()`. So instead of keeping track of whether shift was pressed or not, and which one, you could just use `kaleidoscope::hid::isModifierKeyActive(Key_LeftShift)` to see if its active.

**Comment by tiltowait** [comment]
> Ok, so we have `kaleidoscope::hid::isModifierKeyActive()`. So instead of keeping track of whether shift was pressed or not, and which one, you could just use `kaleidoscope::hid::isModifierKeyActive(Key_LeftShift)` to see if its active.

I'll give that a try.

On some reading, the same source file that has `kaleidoscope::hid::isModifierKeyActive()` also has an anonymous namespace with a function, `isModifierKey()`. Because it's in an anonymous namespace, I can't use it in my plugin, but would there be any problem with copying that function over to my own code? It's a much cleaner, more efficient way of testing if a key is a modifier than what I currently have.

**Comment by tiltowait** [comment]
> [... ]you could just use `kaleidoscope::hid::isModifierKeyActive(Key_LeftShift)` to see if its active.

After a bunch of testing ... I'm not sure `isModifierKeyActive(Key_LeftShift)` actually works. ca842686d28c11cf468bee8c9a675b50ddc2cff9 has my current attempt.
